package com.aopa.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.administrator.happygame.been.Chat;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CHAT".
*/
public class ChatDao extends AbstractDao<Chat, String> {

    public static final String TABLENAME = "CHAT";

    /**
     * Properties of entity Chat.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property UserId = new Property(0, String.class, "userId", true, "USER_ID");
        public final static Property UserName = new Property(1, String.class, "userName", false, "USER_NAME");
        public final static Property UserImageUrl = new Property(2, String.class, "userImageUrl", false, "USER_IMAGE_URL");
        public final static Property LastMessage = new Property(3, String.class, "lastMessage", false, "LAST_MESSAGE");
        public final static Property GetMsgTime = new Property(4, String.class, "getMsgTime", false, "GET_MSG_TIME");
        public final static Property MsgNoRead = new Property(5, int.class, "msgNoRead", false, "MSG_NO_READ");
    }


    public ChatDao(DaoConfig config) {
        super(config);
    }
    
    public ChatDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CHAT\" (" + //
                "\"USER_ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: userId
                "\"USER_NAME\" TEXT," + // 1: userName
                "\"USER_IMAGE_URL\" TEXT," + // 2: userImageUrl
                "\"LAST_MESSAGE\" TEXT," + // 3: lastMessage
                "\"GET_MSG_TIME\" TEXT," + // 4: getMsgTime
                "\"MSG_NO_READ\" INTEGER NOT NULL );"); // 5: msgNoRead
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CHAT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Chat entity) {
        stmt.clearBindings();
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(1, userId);
        }
 
        String userName = entity.getUserName();
        if (userName != null) {
            stmt.bindString(2, userName);
        }
 
        String userImageUrl = entity.getUserImageUrl();
        if (userImageUrl != null) {
            stmt.bindString(3, userImageUrl);
        }
 
        String lastMessage = entity.getLastMessage();
        if (lastMessage != null) {
            stmt.bindString(4, lastMessage);
        }
 
        String getMsgTime = entity.getGetMsgTime();
        if (getMsgTime != null) {
            stmt.bindString(5, getMsgTime);
        }
        stmt.bindLong(6, entity.getMsgNoRead());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Chat entity) {
        stmt.clearBindings();
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(1, userId);
        }
 
        String userName = entity.getUserName();
        if (userName != null) {
            stmt.bindString(2, userName);
        }
 
        String userImageUrl = entity.getUserImageUrl();
        if (userImageUrl != null) {
            stmt.bindString(3, userImageUrl);
        }
 
        String lastMessage = entity.getLastMessage();
        if (lastMessage != null) {
            stmt.bindString(4, lastMessage);
        }
 
        String getMsgTime = entity.getGetMsgTime();
        if (getMsgTime != null) {
            stmt.bindString(5, getMsgTime);
        }
        stmt.bindLong(6, entity.getMsgNoRead());
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public Chat readEntity(Cursor cursor, int offset) {
        Chat entity = new Chat( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // userId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // userName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // userImageUrl
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // lastMessage
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // getMsgTime
            cursor.getInt(offset + 5) // msgNoRead
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Chat entity, int offset) {
        entity.setUserId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setUserName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUserImageUrl(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setLastMessage(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setGetMsgTime(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setMsgNoRead(cursor.getInt(offset + 5));
     }
    
    @Override
    protected final String updateKeyAfterInsert(Chat entity, long rowId) {
        return entity.getUserId();
    }
    
    @Override
    public String getKey(Chat entity) {
        if(entity != null) {
            return entity.getUserId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Chat entity) {
        return entity.getUserId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
