package com.aopa.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.administrator.happygame.been.Activity;
import com.example.administrator.happygame.been.Advertise;
import com.example.administrator.happygame.been.Forum;
import com.example.administrator.happygame.been.News;
import com.example.administrator.happygame.been.User;

import com.aopa.greendao.ActivityDao;
import com.aopa.greendao.AdvertiseDao;
import com.aopa.greendao.ForumDao;
import com.aopa.greendao.NewsDao;
import com.aopa.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig activityDaoConfig;
    private final DaoConfig advertiseDaoConfig;
    private final DaoConfig forumDaoConfig;
    private final DaoConfig newsDaoConfig;
    private final DaoConfig userDaoConfig;

    private final ActivityDao activityDao;
    private final AdvertiseDao advertiseDao;
    private final ForumDao forumDao;
    private final NewsDao newsDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        activityDaoConfig = daoConfigMap.get(ActivityDao.class).clone();
        activityDaoConfig.initIdentityScope(type);

        advertiseDaoConfig = daoConfigMap.get(AdvertiseDao.class).clone();
        advertiseDaoConfig.initIdentityScope(type);

        forumDaoConfig = daoConfigMap.get(ForumDao.class).clone();
        forumDaoConfig.initIdentityScope(type);

        newsDaoConfig = daoConfigMap.get(NewsDao.class).clone();
        newsDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        activityDao = new ActivityDao(activityDaoConfig, this);
        advertiseDao = new AdvertiseDao(advertiseDaoConfig, this);
        forumDao = new ForumDao(forumDaoConfig, this);
        newsDao = new NewsDao(newsDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Activity.class, activityDao);
        registerDao(Advertise.class, advertiseDao);
        registerDao(Forum.class, forumDao);
        registerDao(News.class, newsDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        activityDaoConfig.clearIdentityScope();
        advertiseDaoConfig.clearIdentityScope();
        forumDaoConfig.clearIdentityScope();
        newsDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public ActivityDao getActivityDao() {
        return activityDao;
    }

    public AdvertiseDao getAdvertiseDao() {
        return advertiseDao;
    }

    public ForumDao getForumDao() {
        return forumDao;
    }

    public NewsDao getNewsDao() {
        return newsDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
